package org.meruvian.ldsigner.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FILE_INFO".
 */
public class FileInfo implements java.io.Serializable, LogInformationAware {

    private Long dbId;
    private java.util.Date dbCreateDate;
    private java.util.Date dbUpdateDate;
    private String dbCreateBy;
    private String dbUpdateBy;
    private Integer dbActiveFlag;
    private String id;
    private java.util.Date refCreateDate;
    private String refCreateBy;
    private String originalName;
    private String contentType;
    private String path;
    private Long size;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FileInfo() {
    }

    public FileInfo(Long dbId) {
        this.dbId = dbId;
    }

    public FileInfo(Long dbId, java.util.Date dbCreateDate, java.util.Date dbUpdateDate, String dbCreateBy, String dbUpdateBy, Integer dbActiveFlag, String id, java.util.Date refCreateDate, String refCreateBy, String originalName, String contentType, String path, Long size) {
        this.dbId = dbId;
        this.dbCreateDate = dbCreateDate;
        this.dbUpdateDate = dbUpdateDate;
        this.dbCreateBy = dbCreateBy;
        this.dbUpdateBy = dbUpdateBy;
        this.dbActiveFlag = dbActiveFlag;
        this.id = id;
        this.refCreateDate = refCreateDate;
        this.refCreateBy = refCreateBy;
        this.originalName = originalName;
        this.contentType = contentType;
        this.path = path;
        this.size = size;
    }

    public Long getDbId() {
        return dbId;
    }

    public void setDbId(Long dbId) {
        this.dbId = dbId;
    }

    public java.util.Date getDbCreateDate() {
        return dbCreateDate;
    }

    public void setDbCreateDate(java.util.Date dbCreateDate) {
        this.dbCreateDate = dbCreateDate;
    }

    public java.util.Date getDbUpdateDate() {
        return dbUpdateDate;
    }

    public void setDbUpdateDate(java.util.Date dbUpdateDate) {
        this.dbUpdateDate = dbUpdateDate;
    }

    public String getDbCreateBy() {
        return dbCreateBy;
    }

    public void setDbCreateBy(String dbCreateBy) {
        this.dbCreateBy = dbCreateBy;
    }

    public String getDbUpdateBy() {
        return dbUpdateBy;
    }

    public void setDbUpdateBy(String dbUpdateBy) {
        this.dbUpdateBy = dbUpdateBy;
    }

    public Integer getDbActiveFlag() {
        return dbActiveFlag;
    }

    public void setDbActiveFlag(Integer dbActiveFlag) {
        this.dbActiveFlag = dbActiveFlag;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public java.util.Date getRefCreateDate() {
        return refCreateDate;
    }

    public void setRefCreateDate(java.util.Date refCreateDate) {
        this.refCreateDate = refCreateDate;
    }

    public String getRefCreateBy() {
        return refCreateBy;
    }

    public void setRefCreateBy(String refCreateBy) {
        this.refCreateBy = refCreateBy;
    }

    public String getOriginalName() {
        return originalName;
    }

    public void setOriginalName(String originalName) {
        this.originalName = originalName;
    }

    public String getContentType() {
        return contentType;
    }

    public void setContentType(String contentType) {
        this.contentType = contentType;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getSize() {
        return size;
    }

    public void setSize(Long size) {
        this.size = size;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void setLogInformation(LogInformation logInformation) {
        setRefCreateDate(logInformation.getCreateDate());
        setRefCreateBy(logInformation.getCreateBy());
    }
    // KEEP METHODS END

}
